global:
  scrape_interval: 15s

scrape_configs:
  - job_name: portal-api
    static_configs:
      - targets: ["portal-api:8000"]

  - job_name: ot-sim
    static_configs:
      - targets: ["ot-sim:9000"]
